when:
  - event: push
  - event: cron

matrix:
  IMAGE:
    - alpine-cicd
    - fedora-with-lix
    - pufferpanel-rootless

steps:
  - name: build
    image: quay.io/sapphiccode/alpine-cicd:latest
    directory: ${IMAGE}
    commands:
      - id=$$(docker buildx build --pull --build-arg=SOURCE_DATE_EPOCH=0 --output type=docker,rewrite-timestamp=true -q .)
      - version_cmd=$$(docker image inspect $$id --format '{{ index .Config.Labels "sapphiccode.version.cmd" }}')
      - version=$$(docker run --rm --entrypoint '["sh", "-c"]' $$id "$$version_cmd")
      - echo $$id > .build-id
      - echo $$version > .build-version
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: push
    image: quay.io/sapphiccode/alpine-cicd:latest
    directory: ${IMAGE}
    secrets:
      - QUAY_TOKEN
    commands:
      - echo "$${QUAY_TOKEN}" | docker login -u "sapphiccode+woodpecker" --password-stdin quay.io
      - id=$$(cat .build-id)
      - echo $$id
      - version=$$(cat .build-version)
      - echo $$version
      - |
        for target in quay.io/sapphiccode; do
          repo_path=$$target/${IMAGE}:$$version
          echo $$repo_path
          docker image tag $$id $$repo_path
          docker image push $$repo_path

          repo_path_latest=$$(echo $$repo_path | cut -d ":" -f 1):latest
          docker image tag $$id $$repo_path_latest
          docker image push $$repo_path_latest
        done
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      - event: push
        branch: main
      - event: cron
        cron: nightly
