when:
  - event: push
  - event: cron

depends_on:
  - build

steps:
  - name: clean-up
    image: quay.io/sapphiccode/alpine-cicd:latest
    commands:
      - docker image prune -f
      - docker buildx prune -f
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
