when:
  - event: push
  - event: cron

depends_on:
  - build

steps:
  - name: clean-up
    image: docker.io/library/alpine:latest
    commands:
      - apk add docker-cli docker-cli-buildx
      - docker image prune -f
      - docker buildx prune -f
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
