# .github/workflows/ci.yml

name: Earthly

on:
  push:
  schedule:
    - cron: "42 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.15

      - name: Run build for latest vanilla
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EARTHLY_PUSH: ${{ github.ref == 'refs/heads/main' }}
        run: earthly --ci ./minecraft+build-latest-vanilla
      - name: Run build for everything else
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EARTHLY_PUSH: ${{ github.ref == 'refs/heads/main' }}
        run: earthly --ci ./minecraft+build-latest-all
